#!/usr/bin/env python3
"""
Morning Picks Verifier — Verifies previously generated morning picks against actual market data.

Reads a CSV generated by morning_picks.py, downloads the actual next-day intraday data
from yfinance, checks if the direction, target, and stop-loss were accurate,
and assigns a grade to each pick.
Also provides technical analysis cross-checks (RSI, MACD, VWAP).

Usage:
    python scripts/verify_picks.py --picks picks_2026-03-12.csv
    python scripts/verify_picks.py --picks picks_2026-03-12.csv --no-download
"""

import argparse
import sys
import csv
from pathlib import Path
from datetime import datetime, timedelta

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TimeElapsedColumn

console = Console()

# ── Data Download ────────────────────────────────────────────────────────────

def download_verification_data(symbols: list, date_str: str, cache_dir: Path):
    """
    Download or load 1-minute intraday data for the target verification date.
    yfinance allows 7 days of 1m data.
    """
    import yfinance as yf
    
    cache_dir.mkdir(exist_ok=True, parents=True)
    
    # Parse the target date
    try:
        target_date = datetime.strptime(date_str[:10], "%Y-%m-%d").date()
    except ValueError:
        console.print(f"[red]Invalid date format in CSV: {date_str}[/red]")
        return {}, 0
        
    start_dt = target_date
    end_dt = target_date + timedelta(days=1)
    
    updated = 0
    failed = 0
    stock_dfs = {}

    with Progress(
        SpinnerColumn(), TextColumn("{task.description}"),
        BarColumn(), TextColumn("{task.completed}/{task.total} stocks"),
        TimeElapsedColumn(), console=console, transient=True,
    ) as progress:
        task = progress.add_task("Downloading verification data...", total=len(symbols))

        for symbol in symbols:
            progress.update(task, description=f"Downloading {symbol}...")
            csv_path = cache_dir / f"{symbol}_verify.csv"
            
            try:
                yf_symbol = f"{symbol}.NS"
                ticker = yf.Ticker(yf_symbol)
                
                df = ticker.history(
                    start=start_dt.strftime("%Y-%m-%d"),
                    end=end_dt.strftime("%Y-%m-%d"),
                    interval="1m",
                )

                if df.empty:
                    failed = failed + 1
                    # Try to use cached if available
                    if csv_path.exists():
                        cached_df = pd.read_csv(csv_path, parse_dates=["date"], index_col="date")
                        if len(cached_df) > 0 and cached_df.index[0].date() == target_date:
                            stock_dfs[symbol] = cached_df
                else:
                    df = df.reset_index()
                    df = df.rename(columns={
                        "Datetime": "date", "Open": "open", "High": "high",
                        "Low": "low", "Close": "close", "Volume": "volume",
                    })
                    df["date"] = pd.to_datetime(df["date"]).dt.tz_localize(None)
                    df.set_index("date", inplace=True)
                    df.columns = df.columns.str.lower()
                    
                    df.to_csv(csv_path)
                    stock_dfs[symbol] = df
                    updated = updated + 1
                    
            except Exception:
                failed = failed + 1
                if csv_path.exists():
                    cached_df = pd.read_csv(csv_path, parse_dates=["date"], index_col="date")
                    if len(cached_df) > 0 and cached_df.index[0].date() == target_date:
                        stock_dfs[symbol] = cached_df

            progress.update(task, advance=1)

    return stock_dfs, failed


def load_cached_data(symbols: list, date_str: str, cache_dir: Path):
    """Load cached data without downloading."""
    try:
        target_date = datetime.strptime(date_str[:10], "%Y-%m-%d").date()
    except ValueError:
        return {}
        
    stock_dfs = {}
    for symbol in symbols:
        csv_path = cache_dir / f"{symbol}_verify.csv"
        if csv_path.exists():
            df = pd.read_csv(csv_path, parse_dates=["date"], index_col="date")
            if len(df) > 0 and df.index[0].date() == target_date:
                stock_dfs[symbol] = df
                
    return stock_dfs

# ── Technical Analysis ───────────────────────────────────────────────────────

def compute_ta_indicators(df):
    """Compute basic TA indicators on 1min intraday data."""
    if len(df) < 30:
        return {}

    closes = df["close"].values
    highs = df["high"].values
    lows = df["low"].values
    volumes = df["volume"].values
    
    # RSI (14)
    deltas = np.diff(closes)
    seed = deltas[:14]
    up = seed[seed >= 0].sum() / 14
    down = -seed[seed < 0].sum() / 14
    rs = up / down if down != 0 else 0
    rsi = np.zeros_like(closes)
    rsi[:14] = 100. - 100. / (1. + rs)

    for i in range(14, len(closes)):
        delta = deltas[i - 1]
        if delta > 0:
            upval = delta
            downval = 0.
        else:
            upval = 0.
            downval = -delta
        up = (up * 13 + upval) / 14
        down = (down * 13 + downval) / 14
        rs = up / down if down != 0 else 0
        rsi[i] = 100. - 100. / (1. + rs)
        
    # MACD (12, 26, 9)
    def ema(data, period):
        k = 2 / (period + 1)
        ema_vals = np.zeros_like(data)
        ema_vals[0] = data[0]
        for i in range(1, len(data)):
            ema_vals[i] = data[i] * k + ema_vals[i-1] * (1 - k)
        return ema_vals
        
    ema12 = ema(closes, 12)
    ema26 = ema(closes, 26)
    macd_line = ema12 - ema26
    signal_line = ema(macd_line, 9)
    macd_hist = macd_line - signal_line
    
    # VWAP
    typical_price = (highs + lows + closes) / 3
    vwap = np.cumsum(typical_price * volumes) / np.maximum(np.cumsum(volumes), 1)
    
    # Current values (using first 15 mins to establish morning trend)
    check_idx = min(15, len(df) - 1)
    
    return {
        "rsi": rsi[check_idx],
        "macd_hist": macd_hist[check_idx],
        "macd_trend": "bullish" if macd_hist[check_idx] > 0 else "bearish",
        "vwap_pos": "above" if closes[check_idx] > vwap[check_idx] else "below",
        "vwap_dist": (closes[check_idx] - vwap[check_idx]) / vwap[check_idx]
    }

# ── Verification Logic ───────────────────────────────────────────────────────

def verify_single_pick(pick, df, horizon_bars, market_open="09:15", market_close="15:30"):
    """
    Verify a single pick against actual minute data.
    """
    # Filter to market hours
    df = df.copy()
    df["_time"] = df.index.strftime("%H:%M")
    df = df[(df["_time"] >= market_open) & (df["_time"] < market_close)]
    
    if len(df) == 0:
        return {"error": "No market data available"}
        
    # 1. Establish actual entry
    # Pick entry was based on yesterday's close. We assume we enter at today's open.
    actual_entry = df.iloc[0]["open"]
    entry_time = df.index[0]
    
    is_long = pick["direction"] == "LONG"
    predicted_magnitude = pick["predicted_move_pct"] / 100.0
    
    # Re-calculate SL and Target based on actual entry to be fair
    # Or strict mode: use exact prices from CSV. Here we use exact CSV prices.
    target_price = pick["target_price"]
    sl_price = pick["stop_loss"]
    
    # 2. Simulate the trade over the horizon
    exit_price = actual_entry
    exit_time = entry_time
    exit_reason = "eod"
    max_favorable = 0.0
    max_adverse = 0.0
    
    # Adjust horizon if needed
    bars_to_check = min(horizon_bars, len(df))
    
    # TA Check (first 15 mins)
    ta_data = compute_ta_indicators(df)
    ta_score = 0
    if ta_data:
        if is_long:
            if ta_data["rsi"] < 70 and ta_data["rsi"] > 40: ta_score += 1
            if ta_data["macd_trend"] == "bullish": ta_score += 1
            if ta_data["vwap_pos"] == "above": ta_score += 1
        else:
            if ta_data["rsi"] > 30 and ta_data["rsi"] < 60: ta_score += 1
            if ta_data["macd_trend"] == "bearish": ta_score += 1
            if ta_data["vwap_pos"] == "below": ta_score += 1
            
    # Check bar by bar
    for i in range(1, bars_to_check):
        current_idx = df.index[i]
        curr_high = df.iloc[i]["high"]
        curr_low = df.iloc[i]["low"]
        curr_close = df.iloc[i]["close"]
        
        # Track max excursions
        if is_long:
            fav = (curr_high - actual_entry) / actual_entry
            adv = (curr_low - actual_entry) / actual_entry
        else:
            fav = (actual_entry - curr_low) / actual_entry
            adv = (actual_entry - curr_high) / actual_entry
            
        max_favorable = max(max_favorable, fav)
        max_adverse = min(max_adverse, adv)
        
        # Check SL/TP hits (approximate with high/low)
        if is_long:
            if curr_low <= sl_price:
                exit_price = sl_price
                exit_reason = "stop_loss"
                exit_time = current_idx
                break
            elif curr_high >= target_price:
                exit_price = target_price
                exit_reason = "take_profit"
                exit_time = current_idx
                break
        else:
            if curr_high >= sl_price:
                exit_price = sl_price
                exit_reason = "stop_loss"
                exit_time = current_idx
                break
            elif curr_low <= target_price:
                exit_price = target_price
                exit_reason = "take_profit"
                exit_time = current_idx
                break
                
    # If no trigger hit, use close of the horizon bar
    if exit_reason == "eod":
        exit_idx = min(bars_to_check - 1, len(df) - 1)
        exit_price = df.iloc[exit_idx]["close"]
        exit_time = df.index[exit_idx]
        
    # Calculate actual return
    if is_long:
        actual_return = (exit_price - actual_entry) / actual_entry
        horizon_end_return = (df.iloc[bars_to_check-1]["close"] - actual_entry) / actual_entry
    else:
        actual_return = (actual_entry - exit_price) / actual_entry
        horizon_end_return = (actual_entry - df.iloc[bars_to_check-1]["close"]) / actual_entry
        
    # Grading System
    # A: Direction right, target hit, or return > 80% of target
    # B: Direction right, profitable, but < 80% target
    # C: Direction wrong, but loss < 50% of SL (choppy)
    # D: Direction wrong, loss > 50% of SL
    # F: Direction wrong, SL hit
    
    if actual_return > 0:
        if exit_reason == "take_profit" or actual_return >= 0.8 * predicted_magnitude:
            grade = "A"
        else:
            grade = "B"
    else:
        if exit_reason == "stop_loss":
            grade = "F"
        elif actual_return <= -0.5 * abs((sl_price - pick["entry_price"])/pick["entry_price"]):
            grade = "D"
        else:
            grade = "C"

    return {
        "actual_entry": actual_entry,
        "exit_price": exit_price,
        "exit_time": exit_time.strftime("%H:%M:%S"),
        "exit_reason": exit_reason,
        "actual_return": actual_return * 100,  # percentage
        "horizon_return": horizon_end_return * 100,
        "max_favorable": max_favorable * 100,
        "grade": grade,
        "ta_score": ta_score,
        "ta_data": ta_data
    }


# ── CLI ──────────────────────────────────────────────────────────────────────

def parse_args():
    parser = argparse.ArgumentParser(description="Verify morning picks against actual market data")
    parser.add_argument("--picks", type=str, required=True, help="Path to picks CSV file")
    parser.add_argument("--horizon", type=str, default="", 
                        help="Override horizon (e.g., H60). Defaults to CSV value or H60.")
    parser.add_argument("--no-download", action="store_true", help="Use cached data only")
    parser.add_argument("--save-report", type=str, default="", help="Save verification report as JSON")
    return parser.parse_args()


def main():
    args = parse_args()
    cache_dir = PROJECT_ROOT / ".tmp" / "verify_cache"
    
    # 1. Load picks
    picks = []
    horizon_str = args.horizon
    target_date = None
    
    try:
        with open(args.picks, "r") as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Type conversions
                for k in ["entry_price", "target_price", "stop_loss", "predicted_move_pct", "confidence"]:
                    if k in row:
                        row[k] = float(row[k])
                picks.append(row)
                
                # Extract metadata from first row
                if target_date is None and "picks_for_date" in row and row["picks_for_date"]:
                    target_date = row["picks_for_date"]
                if not horizon_str and "horizon" in row:
                    horizon_str = row["horizon"]
    except FileNotFoundError:
        console.print(f"[red]Could not find picks file: {args.picks}[/red]")
        return
        
    if not picks:
        console.print("[yellow]Picks file is empty.[/yellow]")
        return
        
    if not target_date:
        console.print("[yellow]Warning: Could not determine 'picks_for_date' from CSV, using today.[/yellow]")
        target_date = datetime.now().strftime("%Y-%m-%d")
        
    if not horizon_str:
        horizon_str = "H60"
        
    horizon_bars = int(horizon_str.replace("H", "")) if "H" in horizon_str else 60
    
    console.print(Panel.fit(
        f"[bold cyan]Morning Picks Verifier[/bold cyan]\n"
        f"[dim]Verifying {len(picks)} picks for: {target_date} | Horizon: {horizon_str}[/dim]",
        border_style="cyan"
    ))
    
    symbols = [p["stock"] for p in picks]
    
    # 2. Download/load data
    if args.no_download:
        console.print("[dim]Loading cached market data...[/dim]")
        stock_dfs = load_cached_data(symbols, target_date, cache_dir)
        missing = len(symbols) - len(stock_dfs)
        if missing > 0:
            console.print(f"  [yellow]Missing cached data for {missing} stocks[/yellow]")
    else:
        console.print(f"[dim]Downloading actual market data from yfinance...[/dim]")
        stock_dfs, failed = download_verification_data(symbols, target_date, cache_dir)
        if failed > 0:
            console.print(f"  [yellow]Failed to download data for {failed} stocks[/yellow]")
            
    # 3. Verify each pick
    console.print("\n[bold]Verifying Picks...[/bold]")
    
    results = []
    
    table = Table(show_header=True, header_style="bold magenta")
    table.add_column("Stock", style="bold")
    table.add_column("Dir")
    table.add_column("Grade", justify="center")
    table.add_column("Entry→Exit", justify="right")
    table.add_column("Actual Return", justify="right")
    table.add_column("Pred Return", justify="right", style="dim")
    table.add_column("Exit Reason")
    table.add_column("TA Sync", justify="center")
    
    for pick in picks:
        symbol = pick["stock"]
        if symbol not in stock_dfs:
            table.add_row(symbol, pick["direction"], "N/A", "No Data", "-", "-", "-", "-")
            continue
            
        df = stock_dfs[symbol]
        v = verify_single_pick(pick, df, horizon_bars)
        
        if "error" in v:
            table.add_row(symbol, pick["direction"], "N/A", v["error"], "-", "-", "-", "-")
            continue
            
        # Formatting
        dir_color = "green" if pick["direction"] == "LONG" else "red"
        grade_colors = {"A": "bold green", "B": "green", "C": "yellow", "D": "red", "F": "bold red"}
        grade_str = f"[{grade_colors.get(v['grade'], 'white')}]{v['grade']}[/]"
        
        ret_color = "green" if v["actual_return"] > 0 else "red"
        actual_ret_str = f"[{ret_color}]{v['actual_return']:+.2f}%[/]"
        pred_ret_str = f"{pick['predicted_move_pct']:+.2f}%"
        
        entry_exit = f"{v['actual_entry']:.1f} → {v['exit_price']:.1f}"
        
        ta_stars = "★" * v["ta_score"] + "☆" * (3 - v["ta_score"])
        
        table.add_row(
            symbol,
            f"[{dir_color}]{pick['direction']}[/]",
            grade_str,
            entry_exit,
            actual_ret_str,
            pred_ret_str,
            f"{v['exit_reason']} @ {v['exit_time']}",
            ta_stars
        )
        
        pick.update(v)
        results.append(pick)
        
        
    console.print(table)
    
    # 4. Summary Stats
    if not results:
        console.print("[yellow]No verification results to display.[/yellow]")
        return
        
    correct_dir = sum(1 for r in results if r["actual_return"] > 0)
    avg_ret = sum(r["actual_return"] for r in results) / len(results)
    
    longs = [r for r in results if r["direction"] == "LONG"]
    shorts = [r for r in results if r["direction"] == "SHORT"]
    
    long_acc = sum(1 for r in longs if r["actual_return"] > 0) / len(longs) if longs else 0
    short_acc = sum(1 for r in shorts if r["actual_return"] > 0) / len(shorts) if shorts else 0
    
    grades = {"A": 0, "B": 0, "C": 0, "D": 0, "F": 0}
    for r in results:
        grades[r.get("grade", "N/A")] += 1
        
    console.print(Panel.fit(
        f"[bold]Verification Summary[/bold]\n\n"
        f"Overall Accuracy: [cyan]{correct_dir}/{len(results)} ({correct_dir/len(results)*100:.1f}%)[/cyan]\n"
        f"Average Return:  [{'green' if avg_ret > 0 else 'red'}]{avg_ret:+.2f}%[/]\n\n"
        f"LONG Accuracy:   {long_acc*100:.1f}%\n"
        f"SHORT Accuracy:  {short_acc*100:.1f}%\n\n"
        f"Grades: A:[green]{grades['A']}[/] B:[green]{grades['B']}[/] "
        f"C:[yellow]{grades['C']}[/] D:[red]{grades['D']}[/] F:[bold red]{grades['F']}[/]",
        border_style="cyan"
    ))
    
    # 5. Save report
    if args.save_report:
        import json
        out_path = Path(args.save_report)
        
        # Serialize datetime/date if any
        def default_serializer(obj):
            if isinstance(obj, (np.integer, np.floating)):
                return float(obj)
            if isinstance(obj, np.ndarray):
                return obj.tolist()
            return str(obj)
            
        report = {
            "date": target_date,
            "horizon": horizon_str,
            "total_picks": len(results),
            "accuracy": correct_dir/len(results),
            "average_return": avg_ret,
            "grades": grades,
            "picks": results
        }
        
        with open(out_path, "w") as f:
            json.dump(report, f, indent=2, default=default_serializer)
            
        console.print(f"[green]✓ Saved JSON report to {out_path}[/green]")

if __name__ == "__main__":
    main()
