// Shared types for dashboard API payloads.

export type Metrics = {
  nTrades: number;
  nDays: number;
  winRate: number;
  totalPnl: number;
  meanPnl: number;
  sharpe: number;
  profitFactor: number; // Infinity encoded as a large number / null-safe on client
  maxDrawdown: number;
};

export type CurvePoint = { date: string; value: number };

export type FuturesTrade = {
  id: string;
  tradeDate: string;
  entry: string;
  exit: string;
  side: string;
  entryPx: number;
  exitPx: number;
  netPnl: number;
  exitReason: string;
  regime: string;
  longScore: number;
  source: string;
};

export type VariantRow = { label: string; metrics: Metrics };

export type FeatureImportance = {
  feature: string;
  gainPct: number;
  splits: number;
};

export type HealthCheck = {
  timestamp: string;
  allOk: boolean;
  checks: { name: string; ok: boolean; msg: string }[];
};

export type FuturesPayload = {
  generatedAt: string;
  ledger: {
    totalRows: number;
    dateMin: string;
    dateMax: string;
    nPaper: number;
    nPaperC: number;
    nBootstrap: number;
  };
  validated: Metrics; // forward-walk locked reference (phase3_no_guard)
  liveA: { all: Metrics; t30: Metrics; t5: Metrics; consecLossDays: number };
  liveC: Metrics;
  variants: VariantRow[];
  equityCurve: CurvePoint[]; // full ledger cumulative net PnL
  liveCurve: CurvePoint[]; // live Variant A cumulative net PnL
  recentTrades: FuturesTrade[];
  halts: { hard: string[]; soft: string[] };
  tier1: {
    overallPass: boolean;
    proxyPass: boolean;
    costPass: boolean;
    quintilePass: boolean;
    costRows: {
      cost: number;
      nTrades: number;
      totalPnl: number;
      winRate: number;
      sharpe: number;
      maxDrawdown: number;
    }[];
  } | null;
  features: FeatureImportance[];
  health: HealthCheck | null;
};

export type EquityHolding = { symbol: string; weight: number };

export type EquityRebalance = {
  rebalanceDate: string;
  exitDate: string;
  state: string;
  nHoldings: number;
  turnover: number;
  netRet: number;
  equity: number;
  benchEquity: number;
};

export type EquityPayload = {
  generatedAt: string;
  latest: {
    date: string;
    state: string;
    nHoldings: number;
    equity: number;
    benchEquity: number;
  };
  stats: {
    nRebalances: number;
    dateMin: string;
    dateMax: string;
    totalReturn: number; // equity - 1
    benchReturn: number;
    excessReturn: number;
    investedRate: number; // fraction of periods invested
    avgTurnover: number;
    winRate: number; // fraction of periods with net_ret > 0
  };
  strategyCurve: CurvePoint[];
  benchCurve: CurvePoint[];
  recent: EquityRebalance[];
  latestHoldings: EquityHolding[];
};

export type OpsStep = { label: string; returnCode: number; ok: boolean };

export type EquityPick = {
  symbol: string;
  weight: number;
  score: number;
  price: number;
  advCr: number;
};

export type OpsPayload = {
  generatedAt: string;
  today: string; // IST YYYY-MM-DD
  cron: {
    jobs: { name: string; schedule: string; human: string; entrypoint: string; log: string }[];
    installedAt: string;
  } | null;
  lastRun: {
    source: "daily_run" | "ops_report";
    timestamp: string;
    date: string;
    steps: OpsStep[];
    exitCode: number; // 0 ok · 2 soft halt · 3 hard halt · other = failure
    ranToday: boolean;
  } | null;
  halts: { futures: boolean; equity: boolean };
  eodFetchedToday: boolean; // EOD cache step ok in today's run (Kite token proxy)
  picks: {
    asOf: string;
    generatedAt: string;
    state: string;
    nPicks: number;
    items: EquityPick[];
  } | null;
  futuresToday: { date: string; nTrades: number; net: number } | null;
  health: HealthCheck | null;
};

export type FuturesPlan = {
  stance: string;
  vix: number;
  vixCut: number;
  ret5d: number | null;
  retCut: number;
  tradeable: boolean;
  asOf: string;
  note: string;
  entry: number;
  current: number;
  target: number;
  stop: number;
  roi: number;
  rr: number;
  targetPct: number;
  stopPct: number;
  sizeHint: string;
  lot: number;
  winRate: number | null;
  confidence: number;
};

export type RecPick = {
  symbol: string;
  weight: number;
  score: number;
  price: number;
  advCr: number;
  // trade card (present when generated by morning_run; null on fallback)
  entry: number | null;
  current: number | null;
  target: number | null;
  stop: number | null;
  roi: number | null;
  rr: number | null;
  confidence: number | null;
  horizonDays: number | null;
  sigmaPct: number | null;
};

export type RecommendationsPayload = {
  generatedAt: string;
  asOf: string;
  hasData: boolean;
  equity: { state: string; nPicks: number; items: RecPick[]; config: Record<string, unknown> } | null;
  futures: FuturesPlan | null;
};
